from openai import AsyncOpenAI
from fastapi import HTTPException
from fastapi.responses import StreamingResponse
from app.config import settings
from app.services.embedding_service import embed_text
from app.db.vector_store import similarity_search

client = AsyncOpenAI(api_key=settings.openai_api_key)

CHAT_MODEL = "gpt-4o"

SYSTEM_PROMPT = """
You are a helpful assistant that answers questions based strictly on the provided context.

Rules:
- Only use information from the context below to answer the question
- If the answer is not in the context, say "I couldn't find the answer in the uploaded document"
- Always be concise and precise
- cite the page number where you found the answer at the end of your response like this: (Page 3)
"""
async def generate_answer(question: str, context_chunks: list[dict]) -> str:
    """
    Generate an answer to a question using the provided context chunks.

    Args:
        question: The user's question
        context_chunks: The most relevant chunks from similarity search

    Returns:
        The generated answer as a string

    Raises:
        HTTPException 500: If the OpenAI API call fails
    """
    context = "\n\n".join([
        f"[Page {chunk['page_number']}]: {chunk['content']}"
        for chunk in context_chunks                   
    ])
    try:
        response = await client.chat.completions.create(
            model=CHAT_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {question}"}
            ]
        )
        return response.choices[0].message.content

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate answer: {str(e)}"
        )
    
async def stream_answer(question: str, context_chunks: list[dict]):
    """
    Stream an answer token by token using server sent events.

    Args:
        question: The user's question
        context_chunks: The most relevant chunks from similarity search

    Yields:
        Text tokens as they are generated by the model
    """
    context = "\n\n".join([
        f"[Page {chunk['page_number']}]: {chunk['content']}"
        for chunk in context_chunks
    ])

    try:
        stream = await client.chat.completions.create(
            model=CHAT_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {question}"}
            ],
            stream=True
        )
        async for chunk in stream:
            token = chunk.choices[0].delta.content
            if token is not None:
                yield token

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to stream answer: {str(e)}"
        )

async def query_document(question: str, match_count: int = 5) -> dict:
    """
    Full RAG query pipeline — embed question, find chunks, generate answer.

    Args:
        question: The user's question
        match_count: Number of similar chunks to retrieve (default 5)

    Returns:
        Dict with answer and source chunks
    """
    if not question.strip():
        raise HTTPException(
            status_code=400,
            detail="Question cannot be empty."
        )

    # embed the question
    question_embedding = await embed_text(question)

    #find the most similar chunks
    similar_chunks = await similarity_search(question_embedding, match_count)

    if not similar_chunks:
        raise HTTPException(
            status_code=404,
            detail="No relevant content found. Please upload a document first."
        )

    #generate an answer
    answer = await generate_answer(question, similar_chunks)

    return {
        "answer": answer,
        "sources": [
            {
                "page_number": chunk["page_number"],
                "content": chunk["content"][:200] + "..."
            }
            for chunk in similar_chunks
        ]
    }